import { useNavigate } from 'react-router-dom';
import { GlassCard } from '../components/ui/GlassCard';
import { ArrowLeft } from 'lucide-react';

export default function PrivacyPolicy() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen relative flex flex-col items-center p-6 overflow-hidden bg-[var(--color-bg-dark)]">
      {/* Decorative Blurs */}
      <div className="fixed top-1/4 left-1/4 w-96 h-96 bg-[var(--color-accent-purple)]/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="fixed bottom-1/4 right-1/4 w-96 h-96 bg-[var(--color-accent-cyan)]/10 rounded-full blur-[120px] pointer-events-none" />

      {/* Header */}
      <div className="w-full max-w-4xl flex items-center justify-between p-4 mb-8 relative z-20">
        <button 
          onClick={() => navigate('/')} 
          className="p-2 -ml-2 text-white/50 hover:text-white hover:bg-white/10 rounded-full transition-all"
        >
          <ArrowLeft size={24} />
        </button>
        <div className="text-xl font-bold text-white flex items-center gap-3">
          <img src="/logo.png" alt="Heralune Logo" className="w-8 h-8 object-contain drop-shadow-[0_0_8px_rgba(255,255,255,0.4)]" />
          Heralune
        </div>
        <div className="w-10"></div> {/* Spacer for centering */}
      </div>

      {/* Main Content */}
      <div className="w-full max-w-4xl relative z-10 pb-20">
        <GlassCard className="p-8 md:p-12 shadow-2xl border-white/10" intensity="heavy">
          
          <div className="prose prose-invert prose-p:text-white/70 prose-headings:text-white/90 max-w-none">
            
            <h1 className="text-3xl md:text-4xl font-bold mb-8 text-center bg-clip-text text-transparent bg-gradient-to-r from-white to-white/70">
              Heralune — Legal Documents
            </h1>
            <p className="text-center text-sm text-white/50 italic mb-12">Last updated: August 9, 2026</p>

            <div className="bg-red-500/10 border border-red-500/20 rounded-xl p-6 mb-12 shadow-inner">
              <h2 className="text-red-400 mt-0 mb-4 flex items-center gap-2">
                <span className="text-xl">⚠️</span> Medical Disclaimer
              </h2>
              <p className="font-semibold text-red-200">READ THIS CAREFULLY BEFORE USING HERALUNE.</p>
              <p className="text-red-200/80">Heralune is a journaling and mood-tracking tool. It is not:</p>
              <ul className="text-red-200/80">
                <li>A medical device</li>
                <li>A substitute for professional medical, psychiatric, or psychological advice, diagnosis, or treatment</li>
                <li>A therapy service, telehealth service, or crisis intervention service</li>
                <li>Staffed or reviewed by licensed clinicians, therapists, or physicians</li>
              </ul>
              <p className="text-red-200/80">
                AI-generated insights are not medical opinions. Any reflections, summaries, patterns, or suggestions generated by Heralune's AI features are produced by a large language model (LLM) for personal reflection purposes only. They may be inaccurate, incomplete, or inappropriate for your situation, and must not be relied upon as clinical guidance.
              </p>
              <p className="text-red-200/80 font-medium mt-4">
                If you are experiencing a mental health crisis, having thoughts of suicide or self-harm, or are in danger, do not use this app for help. Instead:
              </p>
              <ul className="text-red-200/80">
                <li>In the U.S.: Call or text 988 (Suicide & Crisis Lifeline), or call 911</li>
                <li>Outside the U.S.: Contact your local emergency number or a local crisis line (see <a href="https://findahelpline.com/" className="text-red-400 hover:underline" target="_blank" rel="noreferrer">findahelpline.com</a>)</li>
                <li>Go to your nearest emergency room</li>
              </ul>
              <p className="text-red-200/80 mb-0 mt-4">
                By using Heralune, you acknowledge and agree that you understand these limitations and that your use of the app is entirely at your own discretion and risk.
              </p>
            </div>

            <hr className="border-white/10 my-12" />

            <h2>Terms of Service</h2>
            
            <h3>1. Acceptance of Terms</h3>
            <p>
              By creating an account or using Heralune ("the App," "we," "us," "our"), you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy. If you do not agree, do not use the App.
              You must be at least 18 years old to use Heralune. If you are using the App on behalf of a minor where permitted by law, you represent that you have the legal authority to do so.
            </p>

            <h3>2. Description of Service</h3>
            <p>
              Heralune provides tools for personal journaling, mood tracking, and AI-generated reflective insights based on entries you voluntarily provide. Insights are generated using third-party large language model infrastructure (see Section 8 and our Privacy Policy).
              Heralune is a wellness and self-reflection tool, not a healthcare service. See the Medical Disclaimer above, which is incorporated into these Terms in full.
            </p>

            <h3>3. Your Account</h3>
            <ul>
              <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You agree to provide accurate information and to notify us promptly of any unauthorized use.</li>
            </ul>

            <h3>4. Your Content</h3>
            <p>
              You own your journal entries, mood logs, and any other content you submit ("User Content").
              By submitting User Content, you grant Heralune a limited, non-exclusive, worldwide license to process, store, and transmit that content solely for the purpose of operating and improving the App's core functionality (e.g., generating your personal insights, syncing across your devices).
              We do not claim ownership of your journal entries. You may export or delete your content at any time. We do not sell your User Content.
            </p>

            <h3>5. Acceptable Use</h3>
            <p>You agree not to:</p>
            <ul>
              <li>Use Heralune for any unlawful purpose</li>
              <li>Attempt to reverse-engineer, scrape, or extract the App's underlying models or systems</li>
              <li>Use the App to harm yourself or others, or to seek instructions for self-harm — the App is not designed for and will not knowingly facilitate such use</li>
              <li>Impersonate another person or misrepresent your identity</li>
              <li>Interfere with or disrupt the App's infrastructure</li>
            </ul>

            <h3>6. AI-Generated Content</h3>
            <p>
              Insights, summaries, prompts, or suggestions generated by Heralune's AI features are automated outputs, not human-reviewed clinical assessments.
              These outputs may contain errors, omissions, or content that does not reflect your actual emotional state.
              You should treat AI-generated insights as a starting point for self-reflection, not as fact or professional guidance. We are not liable for decisions made in reliance on AI-generated content.
            </p>

            <h3>7. Third-Party Services</h3>
            <p>
              Heralune uses third-party infrastructure, including Google's Gemini API, to process journal content and generate AI insights. Your content may be transmitted to and processed by this third-party service subject to their own data processing terms. See our Privacy Policy for details on what data is shared and how it is protected.
            </p>

            <h3>8. Termination</h3>
            <p>
              We may suspend or terminate your account if you violate these Terms. You may delete your account at any time; see the Privacy Policy for what happens to your data upon deletion.
            </p>

            <h3>9. Disclaimers & Limitation of Liability</h3>
            <p className="uppercase text-sm">
              THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE APP, INCLUDING ANY AI-GENERATED INSIGHTS, WILL BE ACCURATE, RELIABLE, OR SUITABLE FOR YOUR MENTAL HEALTH NEEDS.
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, HERALUNE AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO EMOTIONAL DISTRESS, ARISING FROM YOUR USE OF THE APP OR RELIANCE ON ANY AI-GENERATED CONTENT.
            </p>

            <h3>10. Governing Law</h3>
            <p>These Terms are governed by the laws of the United States, without regard to conflict-of-law principles.</p>

            <h3>11. Contact</h3>
            <p>Questions about these Terms? Contact us at support@heralune.com.</p>

            <hr className="border-white/10 my-12" />

            <h2>Privacy Policy</h2>

            <h3>1. Overview</h3>
            <p>
              This Privacy Policy explains how Heralune collects, uses, stores, and protects your personal information, including sensitive journal entries and mood data. Because Heralune deals with emotionally sensitive information, we apply heightened care to how this data is handled.
            </p>

            <h3>2. Information We Collect</h3>
            <ul>
              <li><strong>Account Information:</strong> Email address, authentication data.</li>
              <li><strong>Journaling & Mood Data:</strong> Journal entries, mood logs, tags, timestamps, and any other reflective content you submit.</li>
              <li><strong>AI Interaction Data:</strong> Prompts sent to and outputs received from our AI insight-generation feature (powered by Google's Gemini API).</li>
              <li><strong>Usage Data:</strong> Device type, app version, general usage analytics (collected in aggregate/anonymized form where possible).</li>
            </ul>

            <h3>3. How We Use Your Information</h3>
            <p>We use your data to:</p>
            <ul>
              <li>Provide core app functionality (journaling, mood tracking, syncing)</li>
              <li>Generate personalized AI insights via our AI processing partner</li>
              <li>Improve app performance and features</li>
              <li>Comply with legal obligations</li>
            </ul>
            <p>We do not use your journal content for advertising, and we do not sell your personal data.</p>

            <h3>4. AI Processing & Third-Party Sharing</h3>
            <p>
              To generate insights, relevant portions of your journal entries may be transmitted to Google's Gemini API for processing. This means your content is shared with Google as our AI processing subprocessor, subject to their data processing and retention terms. We configure our integration to limit retention and disable use of your data for third-party model training where such controls are available. We do not otherwise sell or rent your personal data to third parties.
            </p>

            <h3>5. Data Storage & Security</h3>
            <p>
              Data is encrypted in transit (TLS) and at rest. Access to raw journal content is restricted to systems and personnel required to operate the service. Data is securely stored using Supabase infrastructure within the United States. No system is 100% secure; we cannot guarantee absolute security of your data.
            </p>

            <h3>6. Data Retention</h3>
            <p>
              We retain your journal and mood data for as long as your account is active. Upon account deletion, your data is deleted from our active systems within 30 days, except where retention is required by law or for legitimate backup purposes.
            </p>

            <h3>7. Your Rights</h3>
            <p>Depending on your location, you may have the right to:</p>
            <ul>
              <li>Access, correct, or export your data</li>
              <li>Delete your account and associated data</li>
              <li>Withdraw consent to AI processing</li>
              <li>Object to or restrict certain processing</li>
            </ul>
            <p>To exercise these rights, contact privacy@heralune.com.</p>

            <h3>8. Children's Privacy</h3>
            <p>
              Heralune is not directed at children under 13. We do not knowingly collect data from children under this age. If you believe a child has used the App, contact us for prompt deletion.
            </p>

            <h3>9. Changes to This Policy</h3>
            <p>We may update this Privacy Policy periodically. Material changes will be communicated via the App or email prior to taking effect.</p>

            <h3>10. Contact Us</h3>
            <p>For privacy questions or data requests: privacy@heralune.com.</p>
            
          </div>
        </GlassCard>
      </div>
    </div>
  );
}
